version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-test:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - node/test:
          filters:
            branches:
              only:
                - circleci

  deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - "node/run"
            - "node/test"
          app-name: "joke-app-5iw4"
          filters:
            branches:
              only:
                - circleci